
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 21 18:51:55 GMT 2016
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LSQBRACKET = 3;
  public static final int LBRACE = 5;
  public static final int COLON = 7;
  public static final int NUMBER = 9;
  public static final int BOOLEAN = 11;
  public static final int NULL = 8;
  public static final int RSQBRACKET = 4;
  public static final int STRING = 10;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMMA = 2;
  public static final int RBRACE = 6;
}

